version: "3"
services:


  php:
    image: php:7.4-fpm
    volumes:
    - './public:/var/www/html'


  nginx:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - './public:/var/www/html'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'


  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root


